#!/bin/bash +x

# array-2: Use arrays to tally file owners

declare -A files file_group file_owner groups owners

if [[ ! -d "$1" ]]; then
	echo "Usage: array-2 dir" >&2
	exit 1
fi

for i in "$1"/*; do
	owner="$(stat -c %U "$i")" # %U -- by user name of owner
	group="$(stat -c %G "$i")" # %G -- by group name of owner
	files["$i"]="$i"
	file_owner["$i"]="$owner"
	file_group["$i"]="$group"
	((++owners[$owner])) # creating owners array by adding element by element using for loop
	((++groups[$group])) # idem above
done

# List the collected files
{ for i in "${files[@]}"; do
	printf "%-40s %-10s %-10s\n" \ # flag "-" -- left-align the output, 40 or 10 spaces
		"$i" "${file_owner["$i"]}" "${file_group["$i"]}" done } | sort
echo # just a emply line ?

# List groups
echo "File group owners:"
{ for i in "${!groups[@]}"; do
	printf "%-10s: %5d files(s)\n" "$i" "${groups["$i"]}" done } | sort
echo

