#!/bin/bash +x

# hours: script to count files by modification time

usage () {
	echo "Usage: ${0##*/} directory" >&2
}

# check that argument is a directory

if [[ ! -d "$1" ]]; then
	usage
	exit 1
fi

# initialize array
for i in {0..23}; do hours[i]=0; done

#Collect data
# stat -c %y -- use specified format, %y -  time of the last modification; cut -c 12-13 --- select only these characters
for i in $(stat -c %y "$1"/* | cut -c 12-13); do
	j="${i#0}" # for parameter i remove # leading (at the begining) pattern of 0. We extract hours and in the above array hours there were not 0 before hours.
	((++hours[j]))
	((++count))
done

# Display data

echo -e "Hour\tFiles\tHour\tFiles"
echo -e "----\t-----\t----\t-----"
for i in {0..11}; do
	j=$((i + 12))
	printf "%02d\t%d\t%02d\t%d\n" \
			"$i" \
			"${hours[i]}" \
			"$j" \
			"${hours[j]}"
done
printf "\nTotal files = %d\n" $count
 
# for i in ${hours[*]}; do echo $i; done



