#!/bin/bash

# read-integer: evaluate the value of an integer.

read -p "Please enter an integer --> " int

if test -z $int ; then
	echo "Empty space. Please enter an integer" >&2
	exit 1
else 
	if test $int -eq 0 ; then
		echo "$int is zero."
	else
		if test $int -lt 0 ; then
			echo "$int is negative."
		else
			echo "$int is positive."
		fi
		if test $(($int % 2)) -eq 0 ; then
			echo "$int is even."
		else
			echo "$int is odd."
		fi
	fi
fi


