#!/bin/bash

# read-validate: validate input using "test" command.

invalid_input () {
		echo "Invalid input '$REPLY'" >&2
	exit 1
}

read -p "Enter a SINGLE item -> "

# input is empty (invalid).  
test -z "$REPLY"  && invalid_input

# input is multiple items (invalid). Embedded spaces MUST be within quotes."$(command)"--I want only result of the command.
test "$(echo "$REPLY" | wc -w)" -gt 1 && invalid_input

# is input a valid filename?
# "$(locate &REPLY)" is mine contribution!!! uhuu!!! To find file outside current directory.
if test -n "$(echo $REPLY | egrep '^[-[:alnum:]\._]+$')"; then
		echo "'$REPLY' is a valid filename"
	if test -e "$(locate $REPLY)"; then
		echo "and file '$REPLY' exists."
	else
		echo "however, file '$REPLY' does not exist."
	fi


# is input a floating point number?
	if test "$(echo $REPLY | egrep '^-?[[:digit:]]*\.[[:digit:]]+$')"; then
		echo "'$REPLY' is a floating point number."
	else
		echo "'$REPLY' is not a floating point number."
	fi

# is input an integer?
	if test  "$(echo $REPLY | egrep '^-?[[:digit:]]+$')" ; then
		echo "'$REPLY' is an integer."
	else
		echo "'$REPLY' is not an integer."
	fi

else
	echo "The string '$REPLY' is not a valid filename."
fi

